# Dependencies
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# encoding
encoding: utf-8

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rebecca Vislay Wade
tagline:          Neuroscience | Data Science | Analytics
description:      ''
baseurl:          /

author:
  name:           Rebecca Vislay Wade
  url:            https://blog.vislaywade.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
